spring:
  redis: # 网关自己的redis配置
    database: 0
    host: 127.0.0.1
    port: 6379
    system: # macula-cloud的system模块的redis配置
      database: 0
      host: 127.0.0.1
      port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.config.server-addr}
        namespace: ${nacos.config.namespace}
        # group:
    sentinel:
      enabled: false
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 1800
        add-to-simple-url-handler-mapping: true
      routes:
        - id: macula-samples-admin-bff
          uri: lb://macula-samples-admin-bff
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: macula-samples-openapi
          uri: lb://macula-samples-openapi
          predicates:
            - Path=/openapi/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          client-id: e4da4a32-592b-46f0-ae1d-784310e88423
          client-secret: secret
          introspection-uri: http://127.0.0.1:9010/oauth2/introspect
macula:
  gateway:
    security:
      only-auth-urls: /api/**

logging:
  level:
    root: info
  file:
    name: ${user.home}/logs/${spring.application.name}/${spring.application.name}.log
